entity_types:
- Canonical
- Chunk
- Date
- Document
- Entity
- Organization
- Person
- Rationale
- Reference
mode: observed
relation_types:
- ADOPTS
- ALIGNS_WITH
- ALLOWS
- APPLIES_TO
- APPOINT
- ARE_DEFINED_IN
- ARE_USED
- BASED_ON
- CAN_USE
- CARRY_OUT_THEIR_TASKS_AND_ACTIVITIES
- COMPARES
- CONTAINS
- DEDUCE_OR_INFER
- DESERVES_SPECIAL_CONSIDERATION
- DESIGNATE
- DEVELOPED_AND_MANAGED_BY_THE_COMMISSION
- ENSURES
- ESTABLISH
- FACILITATES
- FOR
- FULFIL_TASKS_IN_THE_CONTEXT_OF_CONFORMITY_ASSESSMENT_OF_PRODUCTS_OR_DEVICES_COVERED_BY_THAT_UNION_HARMONISATION_LEGISLATION
- HAS
- HAS_CHUNK
- HOLD
- IMPOSED
- INCLUDES
- INCREASE
- INVOLVES
- IS_INTERPRETED_AS
- IS_THE_ACCESS_TO_AND_ENJOYMENT_OF_CERTAIN_ESSENTIAL_PRIVATE_AND_PUBLIC_SERVICES_AND_BENEFITS
- LIMITS
- LINKS_TO
- MAPS
- MAY_ADOPT_MEASURES_IN_ACCORDANCE_WITH_THE_PRINCIPLE_OF_SUBSIDIARITY_AS_SET_OUT_IN_ARTICLE_5_TEU
- MAY_BE_PROVIDED
- MENTIONS
- OBLIGATIONS_FOR_PROVIDERS_OF_GENERAL-PURPOSE_AI_MODELS_SHOULD_BE_LIMITED_TO
- OF
- OF_REGULATION_(EU)_2024/1689
- ONLY_BE_PLACED_ON_THE_UNION_MARKET
- ONLY_BE_PUT_INTO_SERVICE
- ONLY_BE_USED
- PROHIBITED
- PROHIBITS
- PROPOSES
- PROVIDES
- PROVIDES_INTERPRETIVE_GUIDANCE
- REFERENCE
- REQUIRES
- RESPECT
- SAME_AS
- SET
- SHOULD
- SHOULD_ALLOW_SIMPLIFIED_WAYS_OF_COMPLIANCE_FOR_SMES
- SHOULD_ALSO_APPLY_TO
- SHOULD_ALWAYS_BE_JUDGED
- SHOULD_BE
- SHOULD_BE_A_MEANS_FOR_PROVIDERS_TO_DEMONSTRATE_CONFORMITY_WITH_THE_REQUIREMENTS_OF_THIS_REGULATION
- SHOULD_BE_COMMENSURATE_AND_PROPORTIONATE_TO_THE_TYPE
- SHOULD_BE_ENCOURAGED
- SHOULD_BE_NOTIFIED
- SHOULD_CONSIST_OF
- SHOULD_EXCLUDE_THE_NEED_FOR_COMPLIANCE_FOR_PERSONS_WHO_DEVELOP_OR_USE_MODELS_FOR_NON-PROFESSIONAL_OR_SCIENTIFIC_RESEARCH_PURPOSES
- SHOULD_NEVER_BE_JUDGED
- SHOULD_NOTIFY
- SHOULD_PLAY_A_KEY_ROLE
- SHOULD_TAKE_DUE_ACCOUNT_OF_THE_SIZE_OF_THE_PROVIDER
- USED_IN_THIS_REGULATION
- USES
version: 0
