"""Deterministic follow-up suggestions for the Ask dock.

After each answer, the dock offers up to three chip-style next questions. They are derived
**from the nodes and edges the answer actually returned** — not generated by a model — so
they work in the zero-LLM default, are stable for a given answer, and only ever propose
questions the graph can really act on (every named entity is one the answer surfaced).

The rules are intentionally simple and ordered by usefulness: expand the focus, connect two
things the answer put on screen, or pivot to a different lens (why / timeline / contradictions)
on the same subject. Each suggestion is phrased so the existing router (`classify_query`)
sends it to the intended tool.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from textgraph.console.chat import ChatAnswer

if TYPE_CHECKING:
    from textgraph.l8_retrieval import QueryEngine


def _name(engine: QueryEngine, nid: str) -> str:
    try:
        return engine._name(nid)
    except Exception:
        return nid


def suggest(engine: QueryEngine, ans: ChatAnswer, *, limit: int = 3) -> list[str]:
    """Return up to ``limit`` follow-up questions derived from ``ans``.

    Deterministic and side-effect-free; returns ``[]`` when nothing sensible follows (e.g.
    an abstained answer, where proposing follow-ups would only compound a non-answer).
    """
    if ans.abstained:
        return []

    out: list[str] = []
    seen: set[str] = set()

    def add(q: str) -> None:
        key = q.lower()
        if q and key not in seen:
            seen.add(key)
            out.append(q)

    focus = ans.focus
    focus_name = _name(engine, focus) if focus else None

    # Other entities this answer surfaced, in order, excluding the focus itself.
    others = [n for n in ans.highlight_nodes if n != focus]
    other_names = [_name(engine, n) for n in others]

    if focus_name:
        # 1) Connect the focus to the strongest related entity the answer returned.
        if other_names:
            add(f"How is {focus_name} connected to {other_names[0]}?")
        # 2) Pivot to a different lens on the same subject than the one just used.
        if ans.tool != "neighbors":
            add(f"Who else is connected to {focus_name}?")
        if ans.tool != "why":
            add(f"Why is {focus_name} in this case?")
        if ans.tool != "timeline":
            add(f"What is the timeline of {focus_name}?")

    # For a two-entity answer (path), offer to expand each endpoint.
    if not focus_name and len(other_names) >= 2:
        add(f"Who else is connected to {other_names[0]}?")
        add(f"How is {other_names[0]} connected to {other_names[-1]}?")

    # Tool-specific pivots that don't need a focus.
    if ans.tool in ("communities", "stats"):
        add("Show the contradictions in the graph.")
    if ans.tool == "contradictions" and focus_name:
        add(f"What is the timeline of {focus_name}?")

    # A dependable fallback so the chips are rarely empty on a grounded answer.
    if len(out) < limit:
        add("Show the contradictions in the graph.")

    return out[:limit]
